### ISSUE TITLE
Ambiguous sentence in advinference/multiple_testing.Rmd

### ISSUE THREAD

**Issue by ellisifnygaard** [genomicsclass/labs#100]
(Sorry if this is not the appropriate channel for reporting issues regarding potential typos etc.)

I got confused by the wording "_This implies that with a 0.05 p-value cut-off, out of the 100 tests we incorrectly call between 4 and 5 significant on average._ " in this line:

https://github.com/genomicsclass/labs/blob/c15a1a73ee5d2cf2981e18d29856d6a092f3e70a/advinference/multiple_testing.Rmd#L269
  
Stating "**_the_** 100 tests" made me initially think that the number 100 was supposed to refer to the number of experiments in the Monte Carlo simulation, which was obviously wrong since there are 10,000 experiments/tests for each replication. Did the authors mean something to this effect(?):

> Since there are 9000 tests where the null hypothesis is true and the chosen significance level is 0.05, it follows that we incorrectly call between 400 and 500 tests significant on average (5% of 9000 equals 450) .

**Comment by rafalab** [comment]
I changed it from "out of the 100 tests " to "out of 100 tests". What we mean is that 4/5 out 100 will be false positives.
