### ISSUE TITLE
Permission to port over dplyr tutorial to DataFramesMeta.jl

### ISSUE THREAD

**Issue by pdeffebach** [genomicsclass/labs#102]
Hello, 

I am the maintainer of the Julia package [DataFramesMeta.jl](https://github.com/JuliaData/DataFramesMeta.jl). It is a data manipulation package for the Julia language and it is very similar to dplyr. I would like permission to port your [dplyr](https://github.com/genomicsclass/labs/blob/master/intro/dplyr_tutorial.Rmd) tutorial to DataFramesMeta.jl and host it on our documentation website. 

We are getting very close to releasing version 1.0 of DataFramesMeta and as a result I'm working on tutorials to help new users get on board. 

Because so many of our users will be coming from `dplyr`, it makes sense to not try and re-invent the wheel when it comes to tutorials and instead port over existing tutorials. Your [dplyr tutorial](https://github.com/genomicsclass/labs/blob/master/intro/dplyr_tutorial.Rmd) ranks pretty high on Google search and is a nice introduction. 

Can I modify your tutorial to be a tutorial for DataFramesMeta.jl and host it on our website? This pretty much just involves surface-level syntax changes, but most of the text will remain intact. 

Thank you!

**Comment by rafalab** [comment]
You have permission

**Comment by pdeffebach** [comment]
Thank you!
