### ISSUE TITLE
make an ePub, please

### ISSUE THREAD

**Issue by zhilongjia** [genomicsclass/labs#46]
Could you release an ePub version? When I compiled it by myself, there were lots of errors. Maybe because some files are deprecated. Thank you.

**Comment by mikelove** [comment]
This is already in progress. We will announce it soon, follow @rafalab for
updates.

**Comment by mikelove** [comment]
also, I'm not sure if you already know but the compiled versions of all Rmds are already published as HTML by following the links on the main page, https://github.com/genomicsclass/labs

**Comment by zhilongjia** [comment]
I knew the html version. I also had some problems when making ePub based on the html version. My kindle needs the ePub format. Thank you.

**Comment by mikelove** [comment]
https://leanpub.com/dataanalysisforthelifesciences/
