### ISSUE TITLE
GSE5859 available for R version 3.3.1

### ISSUE THREAD

**Issue by ale07alvarez** [genomicsclass/labs#60]
Is there a GSE5859 available for R version 3.3.1
When running the following command to install the package 

biocLite('GSE5859')
I get the following error 
Warning message:
package ‘GSE5859’ is not available (for R version 3.3.1)
thanks!

**Comment by vjcitn** [comment]
library(devtools)

install_github("genomicsclass/GSE5859Subset")

library(GSE5859Subset)

data(GSE5859Subset)


if that does not work please provide full error trace


also you could do perhaps if interested in the whole series


library(GEOquery)

x = getGEO("GSE5859")

**Comment by ale07alvarez** [comment]
library(devtools)

install_github("genomicsclass/GSE5859Subset")

library(GSE5859Subset)

data(GSE5859Subset)


works thanks!!

**Comment by Yash507** [comment]
library(devtools) install_github("genomicsclass/GSE5859Subset")
 library(GSE5859Subset) data(GSE5859Subset)
