### ISSUE TITLE
Inquiries about solutions for the book's exercise answer

### ISSUE THREAD

**Issue by liutiming** [genomicsclass/labs#70]
Hello! Thanks so much for the fantastic materials here. I am wondering if there are solutions for the exercises in the book Data Analysis for the Life Sciences? I think it will be helpful for the readers to verify the answers.

**Comment by rafalab** [comment]
We do have plans of creating a solutions manual in the future. But, because these exercises are used in our online courses we don't currently make the solutions available. If you register for the online course (note there is a free version), you can see the solutions by trying the assessments.
