### ISSUE TITLE
Error in knitr of all RMD files

### ISSUE THREAD

**Issue by eringiles** [genomicsclass/labs#98]
I'm trying to use the RMD files associated with the Statistics & R course, and I keep getting an error on the first chunk of code:

```{r options, echo=FALSE}
opts_chunk$set(fig.path=paste0("figure/", sub("(.*).Rmd","\\1",basename(knitr:::knit_concord$get('infile'))), "-"))
```

Error says:
Error in basename(knitr:::knit_concord$get("infile")) : a character vector argument expected

Any suggestions?

**Comment by rafalab** [comment]
If you use knitr
```
knitr::knit("filename.Rmd")
```
It should work. If sourcing into R you can comment out that line.

**Comment by sherifrisas** [comment]
Delete the text in the URL that occurs after this pattern.
